//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.25 at 05:28:36 PM CST 
//


package com.hh.test.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Processor" type="{}ProcessorType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="WorkItemURL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ServerAssetURL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ServerSecurityURL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ServerAssetOptionURL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RelaDataServiceURL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="User" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PasswordType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processor"
})
@XmlRootElement(name = "InitConfig")
public class InitConfig {

    @XmlElement(name = "Processor")
    protected List<ProcessorType> processor;
    @XmlAttribute(name = "WorkItemURL")
    protected String workItemURL;
    @XmlAttribute(name = "ServerAssetURL")
    protected String serverAssetURL;
    @XmlAttribute(name = "ServerSecurityURL")
    protected String serverSecurityURL;
    @XmlAttribute(name = "ServerAssetOptionURL")
    protected String serverAssetOptionURL;
    @XmlAttribute(name = "RelaDataServiceURL")
    protected String relaDataServiceURL;
    @XmlAttribute(name = "User")
    protected String user;
    @XmlAttribute(name = "Password")
    protected String password;
    @XmlAttribute(name = "PasswordType")
    protected String passwordType;

    /**
     * Gets the value of the processor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessorType }
     * 
     * 
     */
    public List<ProcessorType> getProcessor() {
        if (processor == null) {
            processor = new ArrayList<ProcessorType>();
        }
        return this.processor;
    }

    /**
     * Gets the value of the workItemURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkItemURL() {
        return workItemURL;
    }

    /**
     * Sets the value of the workItemURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkItemURL(String value) {
        this.workItemURL = value;
    }

    /**
     * Gets the value of the serverAssetURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerAssetURL() {
        return serverAssetURL;
    }

    /**
     * Sets the value of the serverAssetURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerAssetURL(String value) {
        this.serverAssetURL = value;
    }

    /**
     * Gets the value of the serverSecurityURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerSecurityURL() {
        return serverSecurityURL;
    }

    /**
     * Sets the value of the serverSecurityURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerSecurityURL(String value) {
        this.serverSecurityURL = value;
    }

    /**
     * Gets the value of the serverAssetOptionURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerAssetOptionURL() {
        return serverAssetOptionURL;
    }

    /**
     * Sets the value of the serverAssetOptionURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerAssetOptionURL(String value) {
        this.serverAssetOptionURL = value;
    }

    /**
     * Gets the value of the relaDataServiceURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelaDataServiceURL() {
        return relaDataServiceURL;
    }

    /**
     * Sets the value of the relaDataServiceURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelaDataServiceURL(String value) {
        this.relaDataServiceURL = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the passwordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordType() {
        return passwordType;
    }

    /**
     * Sets the value of the passwordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordType(String value) {
        this.passwordType = value;
    }

	@Override
	public String toString() {
		return "InitConfig [processor=" + processor + ", workItemURL=" + workItemURL + ", serverAssetURL="
				+ serverAssetURL + ", serverSecurityURL=" + serverSecurityURL + ", serverAssetOptionURL="
				+ serverAssetOptionURL + ", relaDataServiceURL=" + relaDataServiceURL + ", user=" + user + ", password="
				+ password + ", passwordType=" + passwordType + "]";
	}

    
    
}
